"""empty message

Revision ID: 47b5a5d90c58
Revises: None
Create Date: 2015-05-04 14:48:34.886311

"""

# revision identifiers, used by Alembic.
revision = '47b5a5d90c58'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
